### ISSUE TITLE
Pr.1: La función yTambien e implica hace doble PM

### ISSUE THREAD

**Issue by lucasljm2001** [BautistaBracco/EstrD2023s1#1]
Siempre que se pueda resolver una función analizando un único parámetro, es mejor hacerlo así. Analizar más de un parámetro agrega complejidad y permite que sea fácil olvidar casos.

**Comment by BautistaBracco** [comment]
No importa que tenga que tener en cuenta mas casos? Porque de la única manera que se me ocurre analizar solo un parámetro en las funciones es analizando mas casos

**Comment by BautistaBracco** [comment]
Envié la solución

**Comment by lucasljm2001** [comment]
Resuelto
